package greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import greendao.Sex;
import greendao.User;

import greendao.SexDao;
import greendao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig sexDaoConfig;
    private final DaoConfig userDaoConfig;

    private final SexDao sexDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        sexDaoConfig = daoConfigMap.get(SexDao.class).clone();
        sexDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        sexDao = new SexDao(sexDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Sex.class, sexDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        sexDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public SexDao getSexDao() {
        return sexDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
